### ISSUE TITLE
Custom areas

### ISSUE THREAD

**Issue by Suyashtnt** [kyrptonaught/DiggusMaximus#17]
Add custom areas, like you can make it a 1x2 for hope big enough for the player or a 3x3. 

These are all based on where you mine so the 3x3 will mine all around where the pickaxes is. 

It by default goes 5 blocks feel but you should be able to change that in the UI where you can select the area. Maybe I’ll try to implement the UI once the code is there and learn some fabric(idk how to mod)

**Comment by kyrptonaught** [comment]
I did begin work on this and it’s actually mostly implemented behind the scenes(see [ExcavateTypes](src/main/java/net/kyrptonaught/diggusmaximus/ExcavateTypes.java). I just never got around to finishing it and implementing the UI

**Comment by Suyashtnt** [comment]
Never have I ever gotten a quick response. Thanks for the info

**Comment by Suyashtnt** [comment]
There also seems to be no way to customize it so the user could make a 3x5 or something. Not sure 1how hard that is, maybe once I learn some better modding and the UI is implemented I’ll see how to implement that.

**Comment by kyrptonaught** [comment]
I have notifications set up on my phone :P

It’s still very unpolished, that was just me experimenting with how I’d like to implement it. Perhaps tomorrow I’ll have some time to take another look at it.

Feel free to browse the source of all my mods to help with learning. I’m always open to PRs too!

**Comment by Suyashtnt** [comment]
> I have notifications set up on my phone :P
> 
> It’s still very unpolished, that was just me experimenting with how I’d like to implement it. Perhaps tomorrow I’ll have some time to take another look at it.
> 
> Feel free to browse the source of all my mods to help with learning. I’m always open to PRs too! 

I also :) I’ll also take a look tomorrow, and is it me or does fabric mod code look more readable?

**Comment by Suyashtnt** [comment]
Any updates?

**Comment by Zarepheth** [comment]
I like the idea of controlled shapes for digging - specifically when excavating larger areas of the same material (such as stone, netherrack, etc...).

For mining veins of minerals or chopping trees, the mod's default settings usually work well (at least for small to mid size veins and trees). But when attempting to level a hill, the current method of choosing which blocks to excavate is rather problematic... I end up with tall ridges and deep holes.

It would be great to have configurable digging options at the time one wants to dig. When mining veins of ore, the default is good. When levelling ground, have it take one layer at a time (maybe skipping the block on which the person is standing...). When tunneling, a configurable tunnel size and going away from the player. When chopping trees, starting from the top and working to the bottom (for large trees, whether from mods or things like giant Spruce, Oak, Jungle, or Dark Oak trees - these may have far more than 40 blocks). _hmm, maybe a spiral cut pattern for large 2x2 trees..._

**Comment by kyrptonaught** [comment]
Hey, so I've kinda had this on the back burner for a while now and I apologize. 

But i've got a prerelease version for you guys to test if you're interested.
Recommend using modmenu to be able to see the new in game options. 
Diggus now has basic support for following premade shapes: Layers, Holes, 1x2, and 3x3.
Two new keybindings have been added, one for activating the shape excavation, and one for cycling the currently selected shape(sneak to cycle reverse). 
"Shape Excavating" has the option to ignore the block excavated to dig the shape. Thinking about also adding option to ignore the number of blocks mined, and the distance. 
The rest of Diggus will work identical to before. 
[diggusmaximus-1.5.0-1.16.4.zip](https://github.com/kyrptonaught/DiggusMaximus/files/5762240/diggusmaximus-1.5.0-1.16.4.zip)

**Comment by Zarepheth** [comment]
I gave it try with the "Craft to Exile [Harmony]" mod-pack (disabling the existing version of the mod from the Curse Forge Over Wolf launcher). However, I suffered an error during startup.
[crash-2021-01-03_16.46.19-client.txt](https://github.com/kyrptonaught/DiggusMaximus/files/5762406/crash-2021-01-03_16.46.19-client.txt)

I'm going to try some other experiments, maybe an instance with only this mod...

**Comment by Zarepheth** [comment]
Does the pre-release have any requirements? Like a minimum Minecraft version? A minimum Fabric version? Presence of some version of the Fabric API mod? Any other requirements we should know about?

I'm not making any progress with MultiMC and a vanilla instance of Minecraft 1.16.2 with latest Fabric, the pre-release Diggus Maximus mod, and various combinations of "Fabric API" and "Mod Menu" mods. So far, if the came starts up and runs, there is no vein mining, no indication that I even had installed mods. Or if there's an indication of installed mods - like the "Mods" button is present, it indicates a single mod and the game promptly crashes when I attempt to view the mods. I suppose the crash could be an issue with the version of "Mod Menu" or "Fabric API" I'm using...

**Comment by kyrptonaught** [comment]
The build targets 1.16.4 and fabric api 0.29. It should work with any release of mod menu for 1.16.4. Could you try that?

**Comment by Zarepheth** [comment]
After switching to MC 1.16.4, Mod Menu began working. And then I discovered that Diggus Maximus was not in the mod list. A little further investigation revealed that MultiMC loaded the Zip file without extracting the Jar. Upon correcting that little oversight, I got another error; fixed by removing and replacing Fabric - MultiMC's version change didn't do so well _updating_ Fabric and the mapping files.

Anyway, I eventually got MC and the mod working.

Things to check on:
* My first tunnel, into Stone, returned a single Cobblestone instead of the whole tunnel's worth. Either that, or it returned one cobble for a single Stone block and a bunch of terracotta from the other blocks (my test world started me in a Mesa biome).
* Subsequent tunnels and holes seemed to return the drops from the broken block.
* Using a pickaxe on terracotta, to get a 3x3 section - I expected to get 8 terracotta blocks, but ended up with an unexpected block of red sand that was in the corner of the 3x3 shape. Besides being a different block, it is best broken by a different tool! (The block groupings were empty, so terracotta to sand shouldn't have happened.)

I'll have to do more testing - like with layers and holes. But this is a good start!

**Comment by kyrptonaught** [comment]
In the config you can disable the ignore block to prevent blocks that aren't the same type from being mined

Thank you for testing it!

**Comment by Zarepheth** [comment]
I changed that "ignore block" setting, and that did prevent dissimilar blocks from being mined.
The 3x3 mining was quite helpful in building stairways into the ground - but with the settings change, I sometimes had to individually mine dissimilar blocks from the one in the center of the 3x3 area.

When I was at what I thought a good level for testing the 3x3 tunnel, I mined and got an unexpected result. The first few blocks were okay, but then the tunnel encountered gold ore (my stone pickaxe cannot mine gold). At that point, it stopped digging through those blocks. However, it continued digging in the columns away from me that had no gold ore, leaving minable stone behind the ore.

I was going to screenshot what I saw, but apparently I didn't bind the screenshot key. Since I don't recall the Minecraft default binding, I attempting to enter the Options - Controls to bind my usual key, but the game crashed at that point. Crash log is attached. It seems to be related to Diggus Maximus (I don't have much else installed that could interfere).

[crash-2021-01-04_17.25.57-client.txt](https://github.com/kyrptonaught/DiggusMaximus/files/5767234/crash-2021-01-04_17.25.57-client.txt)

The "layers" and "horizontal layers" both work as I expect (when the "ignore block" setting is disabled).

The 1x2 Tunnel usually works as expected, but in one instance, I ended up with a 1x1 vertical hole in the ground. It is possible the dissimilar block issue being next to the targeted block caused a 1x1 hole instead of a 1x2 hole. My actual intent was to do a horizontal tunnel, but in a poorly lit space, I think I had my cursor on the wrong side of the block...

Just a thought, but could we have a config setting for "small tunnel" and "large tunnel", allowing the player (or server admin) to set the size? 1x2 and 3x3 are fine defaults, but when cutting stairwells, I prefer 3 wide by 4 high, (or even 5 high if adding stair blocks).

As for default groupings, since the mod doesn't come with any, putting all the stone (Stone, Andesite, Granite, Diorite) in a group, all the dirt (Dirt, farmland, grass, coarse dirt, etc...), all the terracotta, all the netherrack into their own groups might make sense, and provide an example for people modifying their configs.

I've also been thinking about trees. This mod works fine for small and mid-size trees, but when dealing with large trees (whether vanilla, or the much larger ones in some mods), this mod could easily leave the upper sections of a tree floating in air, unreachable from the ground. With trees from some mods, it would be nice to group the logs and leaves together, but I'd prefer my tool's durability to only be expended on the logs, not the leaves. Maybe having separate settings for number of mined blocks (and diagonals) for wood versus stone, or perhaps by tool. This tree suggestion might be best for a related mod, instead of this mod. I suspect it could be quite complex to separate which blocks belong to which trees when one gets into leaves that connect trees together.
