### ISSUE TITLE
Crash on gamestart

### ISSUE THREAD

**Issue by MasterEnderman** [kyrptonaught/DiggusMaximus#8]
DiggusMaximus: 1.2.6
Crash Report: https://pastebin.com/qHLV3Zpe

**Comment by kyrptonaught** [comment]
Seems to be an incompatibility with allure, can you see if it works without?

**Comment by MasterEnderman** [comment]
if i disable allure, the game starts fine.

**Comment by kyrptonaught** [comment]
I could try to find a workaround but the real issue is with their mixins. They way they are written causes them to be incompatible with anything trying to make changes to the same place. I’ve seen a few other incompatibilities Bc of this. If their mod wasn’t closed source I would submit a pr fixing the issue but I can’t

**Comment by kyrptonaught** [comment]
For now you could downgrade to 1.2.5 if you don’t need the fixes added in 1.2.6, or remove one of the two mods until this is resolved

**Comment by endavis** [comment]
I added a comment to the Allure curseforge page with a crash report. Hopefully, the author will look at it.

**Comment by kyrptonaught** [comment]
this should be resolved in 1.2.8
